//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC2015.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        public int ID { get; set; }
        [Required]
        [Display(Name ="標題")]
        public string Article_Title { get; set; }
        [Display(Name = "內文")]
        [Required]
        public string Article_Content { get; set; }
        public System.DateTime Article_Create_time { get; set; }
        public System.DateTime Article_Modify_time { get; set; }
        public string create_user_name { get; set; }
    }
}
